name: Execise1
on:
    - workflow_dispatch
    - push
jobs:
    init:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v6
              with:
                node-version: 24
            - uses: actions/checkout@v5
            - run: npm ci
            - name: Build
              run: npm build
            - name: Test
              run: npm test
            - name: Lint
              run: npm lint
            - run: echo "Deploying ..."


