name: Print Issue Event Detail
on:
    issues:
      types: [opened, edited] 
jobs:
    print_event_details:
        runs-on: ubuntu-latest
        steps:
          - run: echo "${{ toJSON(github.event) }}"